name: mitblr_club_app
description: Admin-facing application for registrations and attendance.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  flutter_native_splash: ^2.3.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/src/events/data/event_data.json

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'lib/assets/icon.png'