name: logistics
description: Admin-facing application for registrations and attendance.
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  flutter_native_splash: ^2.4.0
  shared_preferences: ^2.2.2
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logistics/
    - assets/mitblr.club/
    - assets/splash/
    - lib/src/events/data/event_data.json